version: "3.7"
services:
  jupyter:
    build: .
    image: jupyter-custom
    restart: always
    ports:
      - 65333:8888
    volumes:
      - ./data/notebook:/opt/jupyter/notebook
      - ./data/runtime:/opt/jupyter/.local/share/jupyter/runtime/
      - /etc/localtime:/etc/localtime:ro
    networks:
      - jupyter
networks:
  jupyter: {}
