version: "3.7"
services:
  jupyter:
    build: .
    image: jupyter-custom
    restart: always
    ports:
      - 8093:80
    volumes:
      - /srv/data:/var/www/html/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - jupyter
networks:
  jupyter: {}
